let imageWebp=document.querySelector('.loading-screen-ditector');let imageWebpOk=!1;if(imageWebp){if(imageWebp.width+imageWebp.height==0){imageWebpOk=!1}else{imageWebpOk=!0;document.body.classList.add('_webp-!0')}}
function ibg(){let ibg=document.querySelectorAll(".ibg");for(var i=0;i<ibg.length;i++){if(ibg[i].querySelector('._span-img')){if(ibg[i].querySelector('._webp')&&imageWebpOk==!0){ibg[i].style.backgroundImage='url('+ibg[i].querySelector('._webp').dataset.ibg+')';ibg[i].classList.add('_loaded')}else if(ibg[i].querySelector('._jpg')&&imageWebpOk==!1){ibg[i].style.backgroundImage='url('+ibg[i].querySelector('._jpg').dataset.ibg+')';ibg[i].classList.add('_loaded')}}else if(ibg[i].querySelector('._webp')&&ibg[i].querySelector('._jpg')){if(ibg[i].querySelector('._webp')&&imageWebpOk==!0){ibg[i].style.backgroundImage='url('+ibg[i].querySelector('._webp').getAttribute('src')+')';ibg[i].classList.add('_loaded')}else if(ibg[i].querySelector('._jpg')&&imageWebpOk==!1){ibg[i].style.backgroundImage='url('+ibg[i].querySelector('._jpg').getAttribute('src')+')';ibg[i].classList.add('_loaded')}}else{if(ibg[i].querySelector('img')){ibg[i].style.backgroundImage='url('+ibg[i].querySelector('img').getAttribute('src')+')'}}}}
ibg();const iconMenu=document.querySelector('.menu__icon');const menuBody=document.querySelector('.menu__body');if(iconMenu){iconMenu.addEventListener("click",function(e){document.body.classList.toggle('_lock');iconMenu.classList.toggle('_active');menuBody.classList.toggle('_active')})}
let PaddingValue=window.innerWidth-document.querySelector('.wrapper').offsetWidth+'px';document.body.style.paddingRight=PaddingValue;document.querySelector('.heder').style.paddingRight=PaddingValue;document.querySelector('.loading-screen').style.paddingRight=PaddingValue;let Body=document.body;Body.classList.add('_Noloaded');window.onload=function(){let timerinAniItemWrapper=setTimeout(function tick(){Body.classList.remove('_Noloaded');document.body.style.paddingRight=0;document.querySelector('.heder').style.paddingRight=0;document.querySelector('.loading-screen').style.paddingRight=0;Body.classList.add('_loaded')},500)};const heder=document.getElementById('elem');if(heder){let banner=document.querySelector('.Banner');heder.classList.toggle('sticky',window.scrollY>0);window.addEventListener('scroll',function(){heder.classList.toggle('sticky',window.scrollY>0);if(window.scrollY>window.innerHeight*1.5){banner.classList.add('_sticky')}else{banner.classList.remove('_sticky')}})}
const workingMechanism=document.querySelector('.MyServices');if(workingMechanism){const workingMechanismBloks=document.querySelectorAll('.MyServices-flex-block');let workingMechanismNumber=0;for(let i=0;i<workingMechanismBloks.length;i++){let workingMechanismBlok=workingMechanismBloks[i];workingMechanismNumber=workingMechanismNumber+0.2;workingMechanismBlok.style.transitionDelay=`${workingMechanismNumber}s`}}
const happy=document.querySelector('.Happy');if(happy){const happyBloks=document.querySelectorAll('.Happy-flex-block');let happyNumber=-0.2;for(let i=0;i<happyBloks.length;i++){let happyBlok=happyBloks[i];happyNumber=happyNumber+0.2;happyBlok.style.transitionDelay=`${happyNumber}s`}}
const AboutUs=document.querySelector('.AboutUs');if(AboutUs){let aboutUsWrapper=AboutUs.querySelector('.About_Us-left');aboutUsWrapper.addEventListener("click",function(e){aboutUsWrapper.classList.toggle('_active')})}
var swiperMyPortfolio=new Swiper("._MyPortfolio-slider",{direction:"vertical",slidesPerView:1,spaceBetween:100,pagination:{el:"._MyPortfolio-paginachion",clickable:!0,},navigation:{nextEl:".MyPortfolio-slider__button-next",prevEl:".MyPortfolio-slider__button-prev",},breakpoints:{319.1:{allowTouchMove:!1,},767.1:{allowTouchMove:!1,},},});const MyPortfolioPanel=document.querySelector('.MyPortfolio-flex');const MyPortfolioPanelBlocks=MyPortfolioPanel.querySelectorAll('.popup-link');const MyPortfolioSpraitLinkExits=document.querySelectorAll('.sprait-three-blok__exit');const MyPortfolioSpraitWrapper=document.querySelector('.sprait-three-wrapper');const MyPortfoliospraitBloks=document.querySelectorAll('.sprait-three-blok');if(MyPortfolioPanelBlocks){for(let i=0;i<MyPortfolioPanelBlocks.length;i++){let MyPortfolioPanelBlock=MyPortfolioPanelBlocks[i];MyPortfolioPanelBlock.addEventListener("click",function(e){swiperMyPortfolio.slideTo(i)})}}
const popupLinks=document.querySelectorAll('.popup-link');const body=document.querySelector('body');const lockPadding=document.querySelectorAll('.lock-padding');let unlock=!0;const timeout=300;if(popupLinks.length>0){for(let i=0;i<popupLinks.length;i++){const popupLink=popupLinks[i];popupLink.addEventListener("click",function(e){const popupName=popupLink.getAttribute('href').replace('#','');const curentPopup=document.getElementById(popupName);popupOpen(curentPopup);e.preventDefault()})}}
const popupCloseIcon=document.querySelectorAll('.close-popup');if(popupCloseIcon.length>0){for(let i=0;i<popupCloseIcon.length;i++){const el=popupCloseIcon[i];el.addEventListener('click',function(e){popupClose(el.closest('.popup'));e.preventDefault()})}}
function popupOpen(curentPopup){if(curentPopup&&unlock){const popupActive=document.querySelector('.popup.open');if(popupActive){popupClose(popupActive,!1)}else{bodyLock()}
curentPopup.classList.add('open');curentPopup.addEventListener("click",function(e){if(!e.target.closest('.popup__content')){popupClose(e.target.closest('.popup'))}})}}
function popupClose(popupActive,doUnlock=!0){if(unlock){popupActive.classList.remove('open');if(doUnlock){bodyUnlock()}}}
function bodyLock(){const lockPaddingValue=window.innerWidth-document.querySelector('.wrapper').offsetWidth+'px';if(lockPadding.length>0){for(let i=0;i<lockPadding.length;i++){const el=lockPadding[i];el.style.paddingRight=lockPaddingValue}}
body.style.paddingRight=lockPaddingValue;body.classList.add('_lock');unlock=!1;setTimeout(function(){unlock=!0},timeout)}
function bodyUnlock(){setTimeout(function(){if(lockPadding.length>0){for(let i=0;i<lockPadding.length;i++){const el=lockPadding[i];el.style.paddingRight='0px'}}
body.style.paddingRight='0px';body.classList.remove('_lock')},timeout);unlock=!1;setTimeout(function(){unlock=!0},timeout)}
const Forms=document.querySelectorAll('._input-placeholder');if(Forms){for(let i=0;i<Forms.length;i++){let Form=Forms[i];let FormPlaceholder=Form.placeholder;Form.addEventListener("focus",function(e){if(Form.value){Form.classList.add('_valueTru')}else{Form.classList.remove('_valueTru')}});Form.addEventListener("blur",function(e){if(Form.value){Form.classList.add('_valueTru')}else{Form.classList.remove('_valueTru')}})}}
const FormValidationWrappers=document.querySelectorAll('._form-validation__wrapper');if(FormValidationWrappers){for(var i=0;i<FormValidationWrappers.length;i++){let FormValidationWrapper=FormValidationWrappers[i];let FormValidationButton=FormValidationWrapper.querySelector('._form-validation__button');let FormValidationBodys=FormValidationWrapper.querySelectorAll('._form-validation__body');let FormValidationInputs=FormValidationWrapper.querySelectorAll('._form-validation__input');FormValidationButton.addEventListener('click',(e)=>{if(FormValidationInputs.length=FormValidationBodys.length){let sum=0;for(let i=0;i<FormValidationBodys.length;i++){let FormValidationInput=FormValidationInputs[i];let FormValidationBody=FormValidationBodys[i];if(FormValidationInput.getAttribute("type")==="checkbox"){if(FormValidationInput.checked===!0){}else{FormValidationInput.classList.add('error');FormValidationBody.classList.add('error');sum++}}else{if(FormValidationInput.value){console.log("jop")}else{if(!FormValidationInput.classList.contains('error')){FormValidationInput.classList.add('error');console.log(`FormValidationInput = error`)}
if(!FormValidationBody.classList.contains('error')){FormValidationBody.classList.add('error');console.log(`FormValidationBody = error`)}
sum++;console.log(`sum = ${sum}`)}}}
if(sum<=0){FormValidationWrapper.submit()}}});for(let i=0;i<FormValidationInputs.length;i++){let FormValidationInput=FormValidationInputs[i];FormValidationInput.addEventListener('click',(e)=>{for(let i=0;i<FormValidationBodys.length;i++){let FormValidationInput=FormValidationInputs[i];let FormValidationBody=FormValidationBodys[i];FormValidationInput.classList.remove('error');FormValidationBody.classList.remove('error')}})}}}
const anchors=document.querySelectorAll('a[href*="#"]')
for(let anchor of anchors){anchor.addEventListener('click',function(e){if(anchor.classList.contains('_link-click')){e.preventDefault()
const blockID=anchor.getAttribute('href').substr(1)
document.getElementById(blockID).scrollIntoView({behavior:'smooth',block:'start'})}
document.body.classList.remove('_lock');iconMenu.classList.remove('_active');menuBody.classList.remove('_active')})}
const animItems=document.querySelectorAll('._anim-items');let timerinAniItem=setTimeout(function tick(){if(animItems.length>0&&window.innerWidth>1064){window.addEventListener('scroll',animOnScroll);function animOnScroll(){for(let index=0;index<animItems.length;index++){const animItem=animItems[index];const animItemOffset=offset(animItem).top;window.addEventListener('scroll',function(){if((animItemOffset-((window.innerWidth/100)*50))<window.scrollY){animItem.classList.add('_anim-active')}});if((animItemOffset-((window.innerWidth/100)*50))<window.scrollY){animItem.classList.add('_anim-active')}}}
function offset(el){const rect=el.getBoundingClientRect(),scrollleft=window.pageXOffset||document.documentElement.scrollleft,scrollTop=window.pageYOffset||document.documentElement.scrollTop;return{top:rect.top+scrollTop,left:rect.left+scrollleft}}
animOnScroll()}},500)